#!/bin/bash

echo "Reconfigure raspi-gpio-mpdc service..."

set -e

cd "$(dirname "$0")/.."

sudo systemctl stop raspi-gpio-mpdc
sudo cp -u raspi-gpio-mpdc.conf /etc
sudo systemctl start raspi-gpio-mpdc

echo "Waiting for service to restart..."
sleep 5
systemctl status raspi-gpio-mpdc --no-pager -n 5

echo "Done."

